export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const FETCH_USER_ORDERS_REQUEST = 'FETCH_USER_ORDERS_REQUEST'
export const FETCH_USER_ORDERS_SUCCESS = 'FETCH_USER_ORDERS_SUCCESS'
export const FETCH_USER_ORDERS_FAIL = 'FETCH_USER_ORDERS_FAIL'

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL'

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

export const CHANGE_IS_DELIVERED_REQUEST = 'CHANGE_IS_DELIVERED_REQUEST'
export const CHANGE_IS_DELIVERED_SUCCESS = 'CHANGE_IS_DELIVERED_SUCCESS'
export const CHANGE_IS_DELIVERED_FAIL = 'CHANGE_IS_DELIVERED_FAIL'